export const LIMITS = {
  USERNAME_MIN_LENGTH: 3,
  USERNAME_MAX_LENGTH: 30,
  PASSWORD_MIN_LENGTH: 8,
  BIO_MAX_LENGTH: 100,
  JOURNAL_MAX_LENGTH: 280,
  COLLECTION_NAME_MAX_LENGTH: 100,
  MAX_COLLECTIONS: 10,
  MAX_PINNED_GAMES: 3,
  MAX_SCREENSHOTS: 5,
};
